# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  - name: one
    value: onevalue

steps:
  - script: |
      echo ${{ variables.one }}
      echo $(one)
  - bash: |
    env:
      AZURE_CLIENT_ID: $(one)
    displayName: setting env variables for bash
  - powershell: |
    env:
      AZURE_CLIENT_ID: $(one)
    displayName: setting env variables for powershell

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'
